// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.19.4
// source: pkg/grpc/proto/kvado.proto

package kvado

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FindAuthorsByBookNameRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BookName string `protobuf:"bytes,1,opt,name=book_name,json=bookName,proto3" json:"book_name,omitempty"`
}

func (x *FindAuthorsByBookNameRequest) Reset() {
	*x = FindAuthorsByBookNameRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_grpc_proto_kvado_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FindAuthorsByBookNameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindAuthorsByBookNameRequest) ProtoMessage() {}

func (x *FindAuthorsByBookNameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_proto_kvado_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindAuthorsByBookNameRequest.ProtoReflect.Descriptor instead.
func (*FindAuthorsByBookNameRequest) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_proto_kvado_proto_rawDescGZIP(), []int{0}
}

func (x *FindAuthorsByBookNameRequest) GetBookName() string {
	if x != nil {
		return x.BookName
	}
	return ""
}

type FindBooksByAuthorNameRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AuthorName string `protobuf:"bytes,1,opt,name=author_name,json=authorName,proto3" json:"author_name,omitempty"`
}

func (x *FindBooksByAuthorNameRequest) Reset() {
	*x = FindBooksByAuthorNameRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_grpc_proto_kvado_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FindBooksByAuthorNameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindBooksByAuthorNameRequest) ProtoMessage() {}

func (x *FindBooksByAuthorNameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_proto_kvado_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindBooksByAuthorNameRequest.ProtoReflect.Descriptor instead.
func (*FindBooksByAuthorNameRequest) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_proto_kvado_proto_rawDescGZIP(), []int{1}
}

func (x *FindBooksByAuthorNameRequest) GetAuthorName() string {
	if x != nil {
		return x.AuthorName
	}
	return ""
}

type FindBooksByAuthorIDRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AuthorId uint32 `protobuf:"varint,1,opt,name=author_id,json=authorId,proto3" json:"author_id,omitempty"`
}

func (x *FindBooksByAuthorIDRequest) Reset() {
	*x = FindBooksByAuthorIDRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_grpc_proto_kvado_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FindBooksByAuthorIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindBooksByAuthorIDRequest) ProtoMessage() {}

func (x *FindBooksByAuthorIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_proto_kvado_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindBooksByAuthorIDRequest.ProtoReflect.Descriptor instead.
func (*FindBooksByAuthorIDRequest) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_proto_kvado_proto_rawDescGZIP(), []int{2}
}

func (x *FindBooksByAuthorIDRequest) GetAuthorId() uint32 {
	if x != nil {
		return x.AuthorId
	}
	return 0
}

type FindBooksResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Books []*FindBooksResponse_Book `protobuf:"bytes,1,rep,name=books,proto3" json:"books,omitempty"`
}

func (x *FindBooksResponse) Reset() {
	*x = FindBooksResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_grpc_proto_kvado_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FindBooksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindBooksResponse) ProtoMessage() {}

func (x *FindBooksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_proto_kvado_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindBooksResponse.ProtoReflect.Descriptor instead.
func (*FindBooksResponse) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_proto_kvado_proto_rawDescGZIP(), []int{3}
}

func (x *FindBooksResponse) GetBooks() []*FindBooksResponse_Book {
	if x != nil {
		return x.Books
	}
	return nil
}

type FindAuthorsByBookIDRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BookId uint32 `protobuf:"varint,1,opt,name=book_id,json=bookId,proto3" json:"book_id,omitempty"`
}

func (x *FindAuthorsByBookIDRequest) Reset() {
	*x = FindAuthorsByBookIDRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_grpc_proto_kvado_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FindAuthorsByBookIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindAuthorsByBookIDRequest) ProtoMessage() {}

func (x *FindAuthorsByBookIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_proto_kvado_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindAuthorsByBookIDRequest.ProtoReflect.Descriptor instead.
func (*FindAuthorsByBookIDRequest) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_proto_kvado_proto_rawDescGZIP(), []int{4}
}

func (x *FindAuthorsByBookIDRequest) GetBookId() uint32 {
	if x != nil {
		return x.BookId
	}
	return 0
}

type FindAuthorsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Authors []*FindAuthorsResponse_Author `protobuf:"bytes,1,rep,name=authors,proto3" json:"authors,omitempty"`
}

func (x *FindAuthorsResponse) Reset() {
	*x = FindAuthorsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_grpc_proto_kvado_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FindAuthorsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindAuthorsResponse) ProtoMessage() {}

func (x *FindAuthorsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_proto_kvado_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindAuthorsResponse.ProtoReflect.Descriptor instead.
func (*FindAuthorsResponse) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_proto_kvado_proto_rawDescGZIP(), []int{5}
}

func (x *FindAuthorsResponse) GetAuthors() []*FindAuthorsResponse_Author {
	if x != nil {
		return x.Authors
	}
	return nil
}

type FindBooksResponse_Book struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BookId uint32 `protobuf:"varint,1,opt,name=book_id,json=bookId,proto3" json:"book_id,omitempty"`
	Name   string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Genre  string `protobuf:"bytes,3,opt,name=genre,proto3" json:"genre,omitempty"`
	Year   uint32 `protobuf:"varint,4,opt,name=year,proto3" json:"year,omitempty"`
}

func (x *FindBooksResponse_Book) Reset() {
	*x = FindBooksResponse_Book{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_grpc_proto_kvado_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FindBooksResponse_Book) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindBooksResponse_Book) ProtoMessage() {}

func (x *FindBooksResponse_Book) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_proto_kvado_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindBooksResponse_Book.ProtoReflect.Descriptor instead.
func (*FindBooksResponse_Book) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_proto_kvado_proto_rawDescGZIP(), []int{3, 0}
}

func (x *FindBooksResponse_Book) GetBookId() uint32 {
	if x != nil {
		return x.BookId
	}
	return 0
}

func (x *FindBooksResponse_Book) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FindBooksResponse_Book) GetGenre() string {
	if x != nil {
		return x.Genre
	}
	return ""
}

func (x *FindBooksResponse_Book) GetYear() uint32 {
	if x != nil {
		return x.Year
	}
	return 0
}

type FindAuthorsResponse_Author struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AuthorId uint32 `protobuf:"varint,1,opt,name=author_id,json=authorId,proto3" json:"author_id,omitempty"`
	Name     string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *FindAuthorsResponse_Author) Reset() {
	*x = FindAuthorsResponse_Author{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_grpc_proto_kvado_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FindAuthorsResponse_Author) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindAuthorsResponse_Author) ProtoMessage() {}

func (x *FindAuthorsResponse_Author) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_proto_kvado_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindAuthorsResponse_Author.ProtoReflect.Descriptor instead.
func (*FindAuthorsResponse_Author) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_proto_kvado_proto_rawDescGZIP(), []int{5, 0}
}

func (x *FindAuthorsResponse_Author) GetAuthorId() uint32 {
	if x != nil {
		return x.AuthorId
	}
	return 0
}

func (x *FindAuthorsResponse_Author) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_pkg_grpc_proto_kvado_proto protoreflect.FileDescriptor

var file_pkg_grpc_proto_kvado_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x70, 0x6b, 0x67, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2f, 0x6b, 0x76, 0x61, 0x64, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x3b, 0x0a, 0x1c,
	0x46, 0x69, 0x6e, 0x64, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x73, 0x42, 0x79, 0x42, 0x6f, 0x6f,
	0x6b, 0x4e, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09,
	0x62, 0x6f, 0x6f, 0x6b, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x62, 0x6f, 0x6f, 0x6b, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x3f, 0x0a, 0x1c, 0x46, 0x69, 0x6e,
	0x64, 0x42, 0x6f, 0x6f, 0x6b, 0x73, 0x42, 0x79, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x4e, 0x61,
	0x6d, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x61, 0x75, 0x74,
	0x68, 0x6f, 0x72, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a,
	0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x39, 0x0a, 0x1a, 0x46, 0x69,
	0x6e, 0x64, 0x42, 0x6f, 0x6f, 0x6b, 0x73, 0x42, 0x79, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x49,
	0x44, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x61, 0x75, 0x74, 0x68,
	0x6f, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x61, 0x75, 0x74,
	0x68, 0x6f, 0x72, 0x49, 0x64, 0x22, 0xa1, 0x01, 0x0a, 0x11, 0x46, 0x69, 0x6e, 0x64, 0x42, 0x6f,
	0x6f, 0x6b, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2d, 0x0a, 0x05, 0x62,
	0x6f, 0x6f, 0x6b, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x46, 0x69, 0x6e,
	0x64, 0x42, 0x6f, 0x6f, 0x6b, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x42,
	0x6f, 0x6f, 0x6b, 0x52, 0x05, 0x62, 0x6f, 0x6f, 0x6b, 0x73, 0x1a, 0x5d, 0x0a, 0x04, 0x42, 0x6f,
	0x6f, 0x6b, 0x12, 0x17, 0x0a, 0x07, 0x62, 0x6f, 0x6f, 0x6b, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x06, 0x62, 0x6f, 0x6f, 0x6b, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12,
	0x14, 0x0a, 0x05, 0x67, 0x65, 0x6e, 0x72, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x67, 0x65, 0x6e, 0x72, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x79, 0x65, 0x61, 0x72, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x04, 0x79, 0x65, 0x61, 0x72, 0x22, 0x35, 0x0a, 0x1a, 0x46, 0x69, 0x6e,
	0x64, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x73, 0x42, 0x79, 0x42, 0x6f, 0x6f, 0x6b, 0x49, 0x44,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x62, 0x6f, 0x6f, 0x6b, 0x5f,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x62, 0x6f, 0x6f, 0x6b, 0x49, 0x64,
	0x22, 0x87, 0x01, 0x0a, 0x13, 0x46, 0x69, 0x6e, 0x64, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x73,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x35, 0x0a, 0x07, 0x61, 0x75, 0x74, 0x68,
	0x6f, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x46, 0x69, 0x6e, 0x64,
	0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e,
	0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x52, 0x07, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x73, 0x1a,
	0x39, 0x0a, 0x06, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x12, 0x1b, 0x0a, 0x09, 0x61, 0x75, 0x74,
	0x68, 0x6f, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x61, 0x75,
	0x74, 0x68, 0x6f, 0x72, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x32, 0xb3, 0x02, 0x0a, 0x05, 0x4b,
	0x76, 0x61, 0x64, 0x6f, 0x12, 0x46, 0x0a, 0x13, 0x46, 0x69, 0x6e, 0x64, 0x42, 0x6f, 0x6f, 0x6b,
	0x73, 0x42, 0x79, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x49, 0x44, 0x12, 0x1b, 0x2e, 0x46, 0x69,
	0x6e, 0x64, 0x42, 0x6f, 0x6f, 0x6b, 0x73, 0x42, 0x79, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x49,
	0x44, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x12, 0x2e, 0x46, 0x69, 0x6e, 0x64, 0x42,
	0x6f, 0x6f, 0x6b, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x48, 0x0a, 0x13,
	0x46, 0x69, 0x6e, 0x64, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x73, 0x42, 0x79, 0x42, 0x6f, 0x6f,
	0x6b, 0x49, 0x44, 0x12, 0x1b, 0x2e, 0x46, 0x69, 0x6e, 0x64, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72,
	0x73, 0x42, 0x79, 0x42, 0x6f, 0x6f, 0x6b, 0x49, 0x44, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x14, 0x2e, 0x46, 0x69, 0x6e, 0x64, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x73, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4c, 0x0a, 0x15, 0x46, 0x69, 0x6e, 0x64, 0x41, 0x75,
	0x74, 0x68, 0x6f, 0x72, 0x73, 0x42, 0x79, 0x42, 0x6f, 0x6f, 0x6b, 0x4e, 0x61, 0x6d, 0x65, 0x12,
	0x1d, 0x2e, 0x46, 0x69, 0x6e, 0x64, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x73, 0x42, 0x79, 0x42,
	0x6f, 0x6f, 0x6b, 0x4e, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x14,
	0x2e, 0x46, 0x69, 0x6e, 0x64, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x73, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4a, 0x0a, 0x15, 0x46, 0x69, 0x6e, 0x64, 0x42, 0x6f, 0x6f, 0x6b,
	0x73, 0x42, 0x79, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1d, 0x2e,
	0x46, 0x69, 0x6e, 0x64, 0x42, 0x6f, 0x6f, 0x6b, 0x73, 0x42, 0x79, 0x41, 0x75, 0x74, 0x68, 0x6f,
	0x72, 0x4e, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x12, 0x2e, 0x46,
	0x69, 0x6e, 0x64, 0x42, 0x6f, 0x6f, 0x6b, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x42, 0x12, 0x5a, 0x10, 0x74, 0x61, 0x73, 0x6b, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x2f, 0x6b,
	0x76, 0x61, 0x64, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pkg_grpc_proto_kvado_proto_rawDescOnce sync.Once
	file_pkg_grpc_proto_kvado_proto_rawDescData = file_pkg_grpc_proto_kvado_proto_rawDesc
)

func file_pkg_grpc_proto_kvado_proto_rawDescGZIP() []byte {
	file_pkg_grpc_proto_kvado_proto_rawDescOnce.Do(func() {
		file_pkg_grpc_proto_kvado_proto_rawDescData = protoimpl.X.CompressGZIP(file_pkg_grpc_proto_kvado_proto_rawDescData)
	})
	return file_pkg_grpc_proto_kvado_proto_rawDescData
}

var file_pkg_grpc_proto_kvado_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_pkg_grpc_proto_kvado_proto_goTypes = []interface{}{
	(*FindAuthorsByBookNameRequest)(nil), // 0: FindAuthorsByBookNameRequest
	(*FindBooksByAuthorNameRequest)(nil), // 1: FindBooksByAuthorNameRequest
	(*FindBooksByAuthorIDRequest)(nil),   // 2: FindBooksByAuthorIDRequest
	(*FindBooksResponse)(nil),            // 3: FindBooksResponse
	(*FindAuthorsByBookIDRequest)(nil),   // 4: FindAuthorsByBookIDRequest
	(*FindAuthorsResponse)(nil),          // 5: FindAuthorsResponse
	(*FindBooksResponse_Book)(nil),       // 6: FindBooksResponse.Book
	(*FindAuthorsResponse_Author)(nil),   // 7: FindAuthorsResponse.Author
}
var file_pkg_grpc_proto_kvado_proto_depIdxs = []int32{
	6, // 0: FindBooksResponse.books:type_name -> FindBooksResponse.Book
	7, // 1: FindAuthorsResponse.authors:type_name -> FindAuthorsResponse.Author
	2, // 2: Kvado.FindBooksByAuthorID:input_type -> FindBooksByAuthorIDRequest
	4, // 3: Kvado.FindAuthorsByBookID:input_type -> FindAuthorsByBookIDRequest
	0, // 4: Kvado.FindAuthorsByBookName:input_type -> FindAuthorsByBookNameRequest
	1, // 5: Kvado.FindBooksByAuthorName:input_type -> FindBooksByAuthorNameRequest
	3, // 6: Kvado.FindBooksByAuthorID:output_type -> FindBooksResponse
	5, // 7: Kvado.FindAuthorsByBookID:output_type -> FindAuthorsResponse
	5, // 8: Kvado.FindAuthorsByBookName:output_type -> FindAuthorsResponse
	3, // 9: Kvado.FindBooksByAuthorName:output_type -> FindBooksResponse
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_pkg_grpc_proto_kvado_proto_init() }
func file_pkg_grpc_proto_kvado_proto_init() {
	if File_pkg_grpc_proto_kvado_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pkg_grpc_proto_kvado_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FindAuthorsByBookNameRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_grpc_proto_kvado_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FindBooksByAuthorNameRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_grpc_proto_kvado_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FindBooksByAuthorIDRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_grpc_proto_kvado_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FindBooksResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_grpc_proto_kvado_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FindAuthorsByBookIDRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_grpc_proto_kvado_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FindAuthorsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_grpc_proto_kvado_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FindBooksResponse_Book); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_grpc_proto_kvado_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FindAuthorsResponse_Author); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pkg_grpc_proto_kvado_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_grpc_proto_kvado_proto_goTypes,
		DependencyIndexes: file_pkg_grpc_proto_kvado_proto_depIdxs,
		MessageInfos:      file_pkg_grpc_proto_kvado_proto_msgTypes,
	}.Build()
	File_pkg_grpc_proto_kvado_proto = out.File
	file_pkg_grpc_proto_kvado_proto_rawDesc = nil
	file_pkg_grpc_proto_kvado_proto_goTypes = nil
	file_pkg_grpc_proto_kvado_proto_depIdxs = nil
}
